### PR TITLE
Update to JSCS 3.0

### LINKED ISSUE #114: Upgrade jscs to 3.0 up
Hi can you update .jscsrc to be compatible with jscs 3.0^? There are few minor changes eg.
flags verbose and esnext are true by default and are not longer support

### PR DESCRIPTION
**Pull request by martndemus**
Supercedes #115
Fixes #114

### CODE REVIEW

**Comment by raido** [comment]
@brzpegasus @rwjblue Could we fix this? It is quite a blocker with Atom JSCS linter throwing errors for esnext and verbose properties after each typed character.

**Comment by martndemus** [comment]
@raido I'm working on it!

**Comment by fusion2004** [comment]
@martndemus Thank you! If there's anything you need help with, I'm sure some of us (myself included) would be able to pitch in.

**Comment by raido** [comment]
@martndemus Thank you!

**Comment by martndemus** [comment]
@fusion2004 Feel free to pick up fixing failing tests at: https://github.com/minichate/jscs-ember-deprecations/pull/37

**Comment by brzpegasus** [comment]
@martndemus Can you rebase against master?

**Comment by martndemus** [comment]
@brzpegasus Rebased.

There is one more failure that I have a hard time in debugging:

```
Expected token value ":" but = found at acceptance/foo-test.js :
     1 |import Ember from 'ember';
--------^
     2 |import { test } from 'qunit';
     3 |import moduleForAcceptance from '../helpers/module-for-acceptance';
```

**Comment by brzpegasus** [comment]
For reference, the parsing error shown above is a CST issue: https://github.com/cst/cst/issues/118. It needs to be addressed upstream.

**Comment by raido** [comment]
Awesome :)

**Comment by brzpegasus** [comment]
Thanks for the patience!

**Comment by john-kurkowski** [comment]
Was this merged & released prematurely? The description for minichate/jscs-ember-deprecations#37 says it's a blocker for this PR. It has a fix for an undeclared dependency, cst. ember-suave 3.0.0 currently giving me:

```zsh
➜  ember build
Build failed.
The Broccoli Plugin: [] failed with:
Error: Cannot find module 'cst'
```

**Comment by brzpegasus** [comment]
@martndemus fixed the rules for jscs-ember-deprecations, but rather than waiting for that PR to be merged, ember-suave is pulling in the dependency from his branch instead.

The cst error was weird. It was only happening for us during CI builds. We ended up explicitly declaring the dependency in ember-suave, though now that I'm checking again, it probably should have been set as a dependency and not dev dependency.

I'm not at a laptop but for now, would including cst in your project's dependencies allow you to run the build? I'll address this as soon as I'm able to. Thanks for reporting!

**Comment by raido** [comment]
I got CST error as well. Installing it in my project solves the problem but i rather wait for v3.0.1 release.

**Comment by martndemus** [comment]
@brzpegasus / @raido #125 should fix it!

**Comment by hzoo** [comment]
That's really weird - you shouldn't have to include cst because that is included in jscs itself @markelog - not sure if we have an issue with new rules or presets

**Comment by brzpegasus** [comment]
I merged #125 as a temp fix until we figure out what's going on with jscs's cst dependency and presets.

**Comment by brzpegasus** [comment]
@hzoo / @markelog: FYI, there's nothing wrong with `jscs`/`cst`. See the [comment] (https://github.com/DockYard/ember-suave/issues/123#issuecomment-226294107) in #123.

**Comment by brzpegasus** [comment]
@john-kurkowski / @raido: Can you try `ember-suave@3.0.1` and confirm you can now build and run JSCS tests?

**Comment by john-kurkowski** [comment]
👍  3.0.1 works great. Thanks!

**Comment by nem035** [comment]
I'm still getting this error in Atom with `ember-suave@3.0.1`. Any advice on how I can debug this? Is there anything else that needs to be updated besides `ember-suave` package? 

screen shot 2016-06-27 at 12 38 52 pm

**Comment by amyrlam** [comment]
@nem035 it went away for me after I did a `npm install` with `"ember-suave": "3.0.1"` in package.json. I'm using the packages linter, linter-jscs and linter-jshint and they're up to date / Atom restarted etc

**Comment by nem035** [comment]
@amyrlam yeah, reinstalling everything and reopening Atom did it. Thanks. I'm a dummy 😄

**Pull request merged**
