### PR TITLE
Update to JSCS 2.6

### PR DESCRIPTION
**Pull request by seanpdoyle**
Closes [#78].

Deprecate rules and point users upstream.

[#78]: https://github.com/dockyard/ember-suave/issues/78

### CODE REVIEW

**Comment by rwjblue** [comment]
Looks good. We need to enable the new ones in `lib/jscsrc.json` also.

This will have to be pending until 2.6.0 of JSCS is released...

**Comment by seanpdoyle** [comment]
@rwjblue which new ones?

They're already enabled in the JSCS (see `disallowVar` [here](https://github.com/dockyard/ember-suave/blob/master/lib/jscsrc.json#L26))

**Comment by rwjblue** [comment]
Ahh, I didn't pay attention that the upstream rules use the same names.  In that case, we can completely remove our custom rules (because the rule names and values are compatible).  I'd like to keep the good/bad tests though, because I want to use them to auto-generate a style guide #someday.

**Comment by seanpdoyle** [comment]
@rwjblue updated the PR.

I didn't delete https://github.com/dockyard/ember-suave/blob/master/lib/rules/require-template-strings-for-concatenation.js. I also didn't push that upstream, since there is http://jscs.info/rule/requireTemplateStrings.

Is that alright, or is that rule different enough to push upstream as well?

**Comment by rwjblue** [comment]
I wonder if we can add an option to `requireTemplateStrings` upstream to make it pass our tests.

Assuming that is possible, since the rule name is different:

* we would have to keep our rule around (like you did initially in this PR) with a warning suggesting to remove usage of that rule
* update our `lib/jscsrc.json` to use the upstream version

**Comment by seanpdoyle** [comment]
@rwjblue does that rule's `{ "allExcept": ["stringConcatenation"] }`  option cover that functionality?

**Comment by rwjblue** [comment]
You can change it and see if the tests pass, I suspect that what @brzpegasus was mentioning in https://github.com/dockyard/ember-suave/issues/78#issuecomment-156872517 will be an issue.

**Comment by rwjblue** [comment]
https://github.com/jscs-dev/node-jscs/tree/v2.6.0 is released, can you rebase and confirm all is working?

**Comment by seanpdoyle** [comment]
LGTM

**Comment by rwjblue** [comment]
@seanpdoyle - Due to https://github.com/dockyard/ember-suave/blob/master/lib/jscsrc.json#L80, we will be triggering the warning for `requireTemplateStringsForConcatenation` warning to all users of ember-suave.  Can you change our `lib/jscsrc.json` to use `"requireTemplateStrings": { "allExcept": ["stringConcatenation"] }`?

**Comment by rwjblue** [comment]
Actually, in the interest of getting a release out soon to fix the error described in https://github.com/dockyard/ember-suave/issues/84, can you just remove the warning and we can fix that in a subsequent release?

**Comment by seanpdoyle** [comment]
@rwjblue :+1:

**Comment by rwjblue** [comment]
Released in ember-suave@1.2.3.

@seanpdoyle - If you have time, would you mind trying to PR changing from our custom template string rule to the main one, and adding that warning (now that we aren't on a time crunch)?

**Comment by seanpdoyle** [comment]
@rwjblue I think you were right in that they're not equivalent behavior. 

Do we still want to deprecate the custom version?

**Comment by rwjblue** [comment]
> Do we still want to deprecate the custom version?

Yes, once you fix it upstream. :smiling_imp:

**Comment by seanpdoyle** [comment]
:laughing: 

Do you think we'd be better off introducing a new rule or extending the existing rule?

**Comment by rwjblue** [comment]
@seanpdoyle - Lets make a new issue to discuss further.

**Comment by jrowlingson** [comment]
In the workforcetestg1_workers project Anargyros Tomaras has been added as a worker. Adding this same user as a dispatcher fails.

This query ```http://servicesdev.arcgis.com/a910db6b36ff4066a3d4131fccc3da9b/arcgis/rest/services/assignments_ff3c581b47274d8389b9f07f5333783f/FeatureServer/0/query?f=json&returnIdsOnly=true&returnCountOnly=true&where=dispatcherId%3Dundefined&returnGeometry=false&spatialRel=esriSpatialRelIntersects&token=M5PcdfU-OBk1ZzPHyKyonxT-3IiUtiuM6MFEIjNdpQEZHLFPiagnKQT-CmeBdIf5tcWFfUvv1cPVAiY1gM_-tONSqzN5QLs87yyeRraGMEv_qp02_-bM_vSi4yivUOK-25j2rV92Jjv-PrM5M9p6DfUEl-65VhlH_a5VusGLbQULERwaFDanamfYGs-GFGOmrcUb4AbXsgussJlkbZUp_kTfkk2NIZ5F8Q0TZkBHxdMSwLHfhb8cJnLg_VRKCCdH8ueIHcYYQ1zJByzMtzTsdA..``` contains an undefined dispatcherId

**Pull request merged**
