### PR TITLE
Enable requireNumericLiterals rule.

### PR DESCRIPTION
**Pull request by xtian**
https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/require-numeric-literals.js

### CODE REVIEW

**Comment by rwjblue** [comment]
Each bad example needs to be in a separate file to ensure it fails properly. 

Other than that, this looks good (though I've not done any of these parseInt versions before).

**Comment by xtian** [comment]
Yeah, me neither, it just seemed in line with this projects goal of enforcing use of the new syntax.

**Comment by rwjblue** [comment]
Yep. Agreed totally.

**Comment by miguelcobain** [comment]
How are we supposed to parse simple strings into integers?

**Comment by brzpegasus** [comment]
You can use `Number()`, which I believe may be more accurate than `parseInt` since it'll actually return `NaN` if the argument is not valid, unlike `parseInt`, e.g.:

```js
let value = "123abc";
parseInt(value); // => 123
Number(value); // => NaN
```

That said, I was under the impression this rule was only to prevent using `parseInt` with string literals, and mainly for binaries, octals, and hexadecimals (as the [examples](http://jscs.info/rule/requireNumericLiterals) and description suggest). Was the intention of the rule to unconditionally forbid the use of `parseInt` altogether, @hzoo?

**Comment by miguelcobain** [comment]
@brzpegasus Right, but consider this example:

```js
return `rgba(${parseInt(red, 16)}, ${parseInt(green, 16)}, ${parseInt(blue, 16)}, 0.1)`;
```

Using `Number` this would become:

```js
return `rgba(${Number(`0x${red}`)}, ${Number(`0x${green}`)}, ${Number(`0x${blue}`)}, 0.1)`;
```

Aren't nested template strings a bit "too much"? I don't have a very strong opinion on this.

**Comment by rwjblue** [comment]
All of those examples should be fine. This rule should only complain about literal values (not variables).

**Comment by rwjblue** [comment]
Well, based on the rule upstream I am wrong (it seems that it is forbidding all usage of parseInt?!?).

**Comment by miguelcobain** [comment]
Only forbids `parseInt` with radix 2, 8 or 16.

**Comment by hzoo** [comment]
It's probably that I didn't check if the first argument was a literal or not https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/require-numeric-literals.js. (Didn't write enough test cases) Feel free to do a PR and we can backport to 2.x

**Comment by rwjblue** [comment]
Submitted https://github.com/jscs-dev/node-jscs/pull/2133 to fix.

**Pull request merged**
