### PR TITLE
Add generator function code style rules

### PR DESCRIPTION
**Pull request by zeppelin**
Discussion at https://github.com/emberjs/ember.js/pull/12970

### CODE REVIEW

**Comment by rwjblue** [comment]
:+1: from me..

@brzpegasus / @poteto / et al. - r?

**Comment by brzpegasus** [comment]
Thanks for submitting. Obviously, we haven't used generators enough to have a strong opinion on syntax. However, I'm not certain I'm 100% with enforcing a space after `*`. With a shorthand notation, you end up with:

```js
let obj = {
  * createIterator(items) {
    for (let i = 0; i < items.length; i++) {
      yield items[i];
    }
  }
};
```

instead of:

```js
let obj = {
  *createIterator(items) {
    for (let i = 0; i < items.length; i++) {
      yield items[i];
    }
  }
};
```

Even without the shorthand syntax, I'm leaning towards:

```js
let obj = {
  createIterator: function *(items) {
    // ...
  }
};

function *createIterator() {
  // ...
}
```

There's also the use of `*` with `yield`:

```js
yield* [1, 2, 3];
yield * [1, 2, 3];
yield *[1, 2, 3];
```

I want to discuss this more with the DY crew before merging.

**Comment by brzpegasus** [comment]
You could also associate `*` with the `function` or `yield` keyword, rather than the identifier. Then it's evident when looking at the code that this is a special function:

```js
function* foo() {}
```

**Comment by mmun** [comment]
The vast majority of code in the wild uses `function* foo() { }`, though the shorthand syntax does make the problem more interesting...

**Comment by brzpegasus** [comment]
Yeah, @rwjblue, @poteto, and I had a discussion around this earlier, and we had decided that `function* foo() {}` was preferred as well, but that ideally, an exception could be made for the shorthand syntax to allow:

```js
let obj = {
  *foo() { }
};
```

I think that would involve tweaking the rule upstream though. Worse case, I could live with:

```js
let obj = {
  * foo() { }
};
```

Otherwise, the general consensus is to not opt for having a space on each side of `*`.

**Comment by rwjblue** [comment]
@zeppelin - Have you had any time to try to update this as mentioned in https://github.com/DockYard/ember-suave/pull/102#issuecomment-184479423?

**Comment by zeppelin** [comment]
@rwjblue sadly, no :( I would've been okay with a one-liner but cannot devote more time an issue ATM.

**Comment by brzpegasus** [comment]
Closed in favor of #133.

**Pull request closed without merging**
